### ISSUE TITLE
Selected VOC subsets for reproduction

### ISSUE THREAD

**Issue by jiaxi-wu** [sharat29ag/CDAL#1]
Hi~ @sharat29ag
Thanks for your great work. 
Could you share the selected Pascal VOC subsets by CDAL? I hope to reproduce the detection results of active learning.

**Comment by sharat29ag** [comment]
Hi, Jiaxi Wu.
Thank you for your interest in our work.
Sorry, Jiaxi, I have not saved the intermediate selected samples sheets,
you can try to run the code on PASCAL VOC and reproduce the results.
Please note, the initial pool is randomly selected so might need to run a
couple of times to achieve the reported results, as they are an average of
three independent runs.
Let me know if you have any questions.

Thanks
Sharat

**Comment by sharat29ag** [comment]
> Hi~ @sharat29ag
> Thanks for your great work.
> Could you share the selected Pascal VOC subsets by CDAL? I hope to reproduce the detection results of active learning.

Thank you for your interest in our work.
Sorry, Jiaxi, I have not saved the intermediate selected samples sheets, you can try to run the code on PASCAL VOC and reproduce the results. Please note, the initial pool is randomly selected so might need to run a couple of times to achieve the reported results, as they are an average of three independent runs.
Let me know if you have any questions.
