### ISSUE TITLE
the result data of detection

### ISSUE THREAD

**Issue by yyyyytx** [sharat29ag/CDAL#3]
Thanks for your great work.
I research at active learning too, and i did some work about detection on VOC using SSD.
I want to compare the results with data in your paper. But i cannot find the exact mAP data in your paper and supplements.
Could you provide the exact mAP numbers to this email?   369430137@qq.com
Thanks for your great work again.

**Comment by sharat29ag** [comment]
> Thanks for your great work.
> I research at active learning too, and i did some work about detection on VOC using SSD.
> I want to compare the results with data in your paper. But i cannot find the exact mAP data in your paper and supplements.
> Could you provide the exact mAP numbers to this email? [369430137@qq.com](mailto:369430137@qq.com)
> Thanks for your great work again.

Thank you for noticing our work. 
mAP reported for pascal VOC is an average of three independent runs. Sorry I do not have exact mAP for each AL cycle. You can try to run our code for one cycle, you will get approx results as the standard deviation was not high.
