### ISSUE TITLE
image classification features to be passes

### ISSUE THREAD

**Issue by razvancaramalau** [sharat29ag/CDAL#4]
Thank you so much for sharing the code. Paper and work are really interesting. For the image classification scenario and also on the second set of features from your repo, the "reward" goes to "nan"  after the first epoch and it throws assertion failure. Can you advise me on the parameters or settings for how to overcome this? Thank you in advance! (For image classification we pass the features array: number_of_features X batch << of unlabelled>>? For the segmentation there are 19/20)

**Comment by sharat29ag** [comment]
> Thank you so much for sharing the code. Paper and work are really interesting. For the image classification scenario and also on the second set of features from your repo, the "reward" goes to "nan" after the first epoch and it throws assertion failure. Can you advise me on the parameters or settings for how to overcome this? Thank you in advance! (For image classification we pass the features array: number_of_features X batch << of unlabelled>>? For the segmentation there are 19/20)

The input feature for the classification task will be a vector [number of classx1], for example in CIFAR10 it will be 10x1. Rest the hyperparameters for the RL are mentioned in the paper, keep a check on the cell size for the LSTM.
